version: '3.0'
services:
  nodo1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: nodo1
    ports:
      - 8080:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
